### ISSUE TITLE
Quick Launch doesn’t work

### ISSUE THREAD

**Issue by KenLPham** [KenLPham/AppSelector#6]
When trying to respond to a iMessage notification, keyboard and message wouldn’t load

**Comment by avitzavi** [comment]
Same issue. When swiping down on a banner the keyboard and message doesn’t load. IPX 12.1.1

**Comment by KenLPham** [comment]
Fixed v1.0.2

**Comment by avitzavi** [comment]
Still happens in latest update

**Comment by KenLPham** [comment]
Fixed 1.0.3
